### ISSUE TITLE
Cannot use in App Engine

### ISSUE THREAD

**Issue by ernestoalejo** [naoina/go-stringutil#1]
After the commit https://github.com/naoina/go-stringutil/commit/915b2f950394c54fec72e8462a5d223e3fd5f775 this library depends on code using `unsafe` which is forbidden in the App Engine runtime. Is there some way to get rid of the `unsafe` import? There is a build constraint `appengine` that can be used if needed.

I opened the issue here because `github.com/naoina/toml` uses this library. It would be also ok if it's changed in the other project.

**Comment by naoina** [comment]
@ernestoalejo 

Thank you for your report.
I made a change so that it does not use `unsafe` in the latest commit https://github.com/naoina/go-stringutil/commit/6b638e95a32d0c1131db0e7fe83775cbea4a0d0b.
I think this issue has been resolved, but please check at your end because I don't have used `appengine`.

**Comment by ernestoalejo** [comment]
I have deployed a new version of the app with the new code and it's ok now. Thank you!
